// constants/sidebar.ts
import {
    Home,
    BookOpen,
    Calendar,
    BarChart2,
    MessageCircle,
    CreditCard,
    FileText,
    LogOut,
    Users,
    User,
    Plus,
    ClipboardList,
    Send,
    Settings,
    Layout,
    GraduationCap,
    UserPlus,
    UserCheck,
    File,
    Award,
    Newspaper,
    Scroll,
    AwardIcon,
    DollarSign,
    ChartColumn,
    Settings2,
    LayoutDashboard,
    Briefcase,
    MessageSquare,
    House,
    CalendarClock,
    CalendarDays,
    Trash2,
} from "lucide-react";
import { SidebarItem } from "../types/sidebar";
import { Permission } from "../enums/permissions";

export const PARENT_MENU_ITEMS: SidebarItem[] = [
    {
        label: "Analytics",
        description: "Performance Insights",
        tab: "analytics",
        href: "/frontend/pages/parent?tab=analytics",
        icon: ChartColumn,
        permission: Permission.ANALYTICS,
    requiresSubscription: true,
    },
    {
        label: "Home",
        tab: "dashboard",
        href: "/frontend/pages/parent?tab=dashboard",
        icon: House,
        permission: Permission.HOME,
    requiresSubscription: true,
    },
    {
        label: "Profile",
        tab: "profile",
        href: "/frontend/pages/parent?tab=profile",
        icon: User,
        permission: Permission.PROFILE,
        requiresSubscription: false,
    },
    {
        label: "Homework",
        tab: "homework",
        href: "/frontend/pages/parent?tab=homework",
        icon: BookOpen,
        permission: Permission.HOMEWORK,
    requiresSubscription: true,
    },
    {
        label: "Timetable",
        tab: "timetable",
        href: "/frontend/pages/parent?tab=timetable",
        icon: CalendarDays,
        permission: Permission.TIMETABLE,
    requiresSubscription: true,
    },
    {
        label: "Attendance",
        tab: "attendance",
        href: "/frontend/pages/parent?tab=attendance",
        icon: Calendar,
        permission: Permission.ATTENDANCE,
    requiresSubscription: true,
    },
    {
        label: "Marks",
        tab: "marks",
        href: "/frontend/pages/parent?tab=marks",
        icon: Award,
        permission: Permission.MARKS,
    requiresSubscription: true,
    },
    {
        label: "Exams & Syllabus",
        tab: "exams",
        href: "/frontend/pages/parent?tab=exams",
        icon: ClipboardList,
        permission: Permission.EXAMS,
    requiresSubscription: true,
    },
    {
        label: "Chat",
        tab: "chat",
        href: "/frontend/pages/parent?tab=chat",
        icon: MessageCircle,
        permission: Permission.CHAT,
    requiresSubscription: true,
    },
    {
        label: "Workshops",
        tab: "workshops",
        href: "/frontend/pages/parent?tab=workshops",
        icon: Briefcase,
        permission: Permission.WORKSHOPS,
    requiresSubscription: true,
    },
    {
        label: "Certificates",
        tab: "certificates",
        href: "/frontend/pages/parent?tab=certificates",
        icon: FileText,
        permission: Permission.CERTIFICATES,
    requiresSubscription: true,
    },
    {
        label: "Fees",
        tab: "fees",
        href: "/frontend/pages/parent?tab=fees",
        icon: CreditCard,
        permission: Permission.FEES,
        requiresSubscription: false,
    },
    {
        label: "Leave Application",
        tab: "leave",
        href: "/frontend/pages/parent?tab=leave",
        icon: CalendarClock,
        permission: Permission.STUDENT_LEAVE,
    requiresSubscription: true,
    },
    {
        label: "Settings",
        tab: "settings",
        href: "/frontend/pages/parent?tab=settings",
        icon: Settings,
        permission: Permission.SETTINGS,
    requiresSubscription: false,
    },
    {
        label: "Subscription",
        tab: "subscription",
        href: "/frontend/pages/parent?tab=subscription",
        icon: CreditCard,
        permission: Permission.FEES,
        requiresSubscription: false,
    },
    {
        label: "Logout",
        icon: LogOut,
        action: "logout",
    },
];



export const SCHOOLADMIN_MENU_ITEMS: SidebarItem[] = [
    {
        label: "Dashboard",
        tab: "dashboard",
        href: "/frontend/pages/schooladmin?tab=dashboard",
        icon: Layout,
        permission: Permission.DASHBOARD,
    },
    {
        label: "Classes",
        tab: "classes",
        href: "/frontend/pages/schooladmin?tab=classes",
        icon: GraduationCap,
        permission: Permission.CLASSES,
    },
    {
        label: "Students",
        tab: "students",
        href: "/frontend/pages/schooladmin?tab=students",
        icon: Users,
        permission: Permission.STUDENTS,
    },
    {
        label: "Admission",
        tab: "admission",
        href: "/frontend/pages/schooladmin?tab=admission",
        icon: UserPlus,
        permission: Permission.ADMISSION,
    },
    {
        label: "Add User",
        tab: "add-user",
        href: "/frontend/pages/schooladmin?tab=add-user",
        icon: UserPlus,
        permission: Permission.NEW_USER,
    }, {
        label: "Student Details",
        tab: "student-details",
        href: "/frontend/pages/schooladmin?tab=student-details",
        icon: User,
        permission: Permission.STUDENT_DETAILS,
    },
    {
        label: "Teachers",
        tab: "teachers",
        href: "/frontend/pages/schooladmin?tab=teachers",
        icon: UserCheck,
        permission: Permission.TEACHERS,
    },
    {
        label: "Timetable",
        tab: "timetable",
        href: "/frontend/pages/schooladmin?tab=timetable",
        icon: CalendarDays,
        permission: Permission.TIMETABLE,
    },
    {
        label: "Teacher Leaves",
        tab: "teacher-leaves",
        href: "/frontend/pages/schooladmin?tab=teacher-leaves",
        icon: FileText,
        permission: Permission.TEACHER_LEAVES,
    },
    {
        label: "Teacher Audit",
        tab: "teacher-audit",
        href: "/frontend/pages/schooladmin?tab=teacher-audit",
        icon: Award,
        permission: Permission.TEACHER_AUDIT,
    },
    {
        label: "Workshops & Events",
        tab: "workshops",
        href: "/frontend/pages/schooladmin?tab=workshops",
        icon: Calendar,
        permission: Permission.WORKSHOPS,
    },
    {
        label: "Newsfeed",
        tab: "newsfeed",
        href: "/frontend/pages/schooladmin?tab=newsfeed",
        icon: Newspaper,
        permission: Permission.NEWSFEED,
    }, {
        label: "Circulars",
        tab: "circulars",
        href: "/frontend/pages/schooladmin?tab=circulars",
        icon: Scroll,
        permission: Permission.CIRCULARS,
    },
    {
        label: "Certificate Request",
        tab: "certificates",
        href: "/frontend/pages/schooladmin?tab=certificates",
        icon: AwardIcon,
        permission: Permission.CERTIFICATES,
    },
    {
        label: "Fees",
        tab: "fees",
        href: "/frontend/pages/schooladmin/fees",
        icon: DollarSign,
        permission: Permission.FEES,
    },
    {
        label: "Exams",
        tab: "exams",
        href: "/frontend/pages/schooladmin?tab=exams",
        icon: ClipboardList,
        permission: Permission.EXAMS,
    },
    {
        label: "Marks",
        tab: "marks",
        href: "/frontend/pages/schooladmin?tab=marks",
        icon: Award,
        permission: Permission.MARKS,
    },
    {
        label: "Analysis",
        tab: "analysis",
        href: "/frontend/pages/schooladmin/analysis",
        icon: ChartColumn,
        permission: Permission.ANALYSIS,
    },
    {
        label: "Settings",
        tab: "settings",
        href: "/frontend/pages/schooladmin?tab=settings",
        icon: Settings,
        permission: Permission.SETTINGS,
    },
    {
        label: "Logout",
        icon: LogOut,
        action: "logout",
    },
];

export const SCHOOLADMIN_TAB_TITLES: Record<string, string> = {
    dashboard: "Dashboard",
    students: "Students",
    admission: "Admission",
    teachers: "Teachers",
    classes: "Classes",
    "teacher-leaves": "Teacher Leaves",
    "tc-approvals": "TC Approvals",
    payments: "Payments",
    workshops: "Workshops & Events",
    newsfeed: "Newsfeed",
    exams: "Exams",
    marks: "Marks",
    analysis: "Analysis",
    "student-details": "Student Details",
    "add-user": "Add User",
    "teacher-audit": "Teacher Audit",
    timetable: "Timetable",
    circulars: "Circulars",
    certificates: "Certificate Requests",
    fees: "Fees",
    settings: "Settings",
};

export const TEACHER_MENU_ITEMS: SidebarItem[] = [
    {
        label: "Dashboard",
        tab: "dashboard",
        href: "/frontend/pages/teacher?tab=dashboard",
        icon: LayoutDashboard,
        permission: Permission.DASHBOARD,
    },
    {
        label: "Admission",
        tab: "admission",
        href: "/frontend/pages/teacher?tab=admission",
        icon: UserPlus,
        permission: Permission.ADMISSION,
    },
    {
        label: "Classes",
        tab: "classes",
        href: "/frontend/pages/teacher?tab=classes",
        icon: GraduationCap,
        permission: Permission.CLASSES,
    },
    {
        label: "Students",
        tab: "students",
        href: "/frontend/pages/teacher?tab=students",
        icon: Users,
        permission: Permission.STUDENTS,
    },
    {
        label: "Student Details",
        tab: "student-details",
        href: "/frontend/pages/teacher?tab=student-details",
        icon: User,
        permission: Permission.STUDENT_DETAILS,
    },
    {
        label: "Teachers",
        tab: "teachers",
        href: "/frontend/pages/teacher?tab=teachers",
        icon: UserCheck,
        permission: Permission.TEACHERS,
    },
    {
        label: "Teacher Leaves",
        tab: "teacher-leaves",
        href: "/frontend/pages/teacher?tab=teacher-leaves",
        icon: FileText,
        permission: Permission.TEACHER_LEAVES,
    },
    {
        label: "Teacher Audit",
        tab: "teacher-audit",
        href: "/frontend/pages/teacher?tab=teacher-audit",
        icon: Award,
        permission: Permission.TEACHER_AUDIT,
    },
    {
        label: "Certificate Request",
        tab: "certificates",
        href: "/frontend/pages/teacher?tab=certificates",
        icon: AwardIcon,
        permission: Permission.CERTIFICATES,
    },
    {
        label: "Fees & Payments",
        tab: "fees",
        href: "/frontend/pages/teacher?tab=fees",
        icon: DollarSign,
        permission: Permission.FEES,
    },
    {
        label: "Homework",
        tab: "homework",
        href: "/frontend/pages/teacher?tab=homework",
        icon: BookOpen,
        permission: Permission.HOMEWORK,
    },
    {
        label: "Timetable",
        tab: "timetable",
        href: "/frontend/pages/teacher?tab=timetable",
        icon: CalendarDays,
        permission: Permission.TIMETABLE,
    },
    {
        label: "Marks",
        tab: "marks",
        href: "/frontend/pages/teacher?tab=marks",
        icon: Award,
        permission: Permission.MARKS,
    },
    {
        label: "Attendance",
        tab: "attendance",
        href: "/frontend/pages/teacher?tab=attendance",
        icon: Calendar,
        permission: Permission.ATTENDANCE,
    },
    {
        label: "Exams & Syllabus",
        tab: "exams",
        href: "/frontend/pages/teacher?tab=exams",
        icon: FileText,
        permission: Permission.EXAMS,
    },
    {
        label: "Worksops & Events",
        tab: "workshops",
        href: "/frontend/pages/teacher?tab=workshops",
        icon: Briefcase,
        permission: Permission.WORKSHOPS,
    }, {
        label: "Newsfeed",
        tab: "newsfeed",
        href: "/frontend/pages/teacher?tab=newsfeed",
        icon: Newspaper,
        permission: Permission.NEWSFEED,
    }, {
        label: "Parent Chat",
        tab: "chat",
        href: "/frontend/pages/teacher?tab=chat",
        icon: MessageSquare,
        permission: Permission.CHAT,
    },
    {
        label: "Leave",
        tab: "leaves",
        href: "/frontend/pages/teacher?tab=leaves",
        icon: FileText,
        permission: Permission.LEAVES,
    },
    {
        label: "Profile",
        tab: "profile",
        href: "/frontend/pages/teacher?tab=profile",
        icon: User,
        permission: Permission.PROFILE,
    },
    {
        label: "Settings",
        tab: "settings",
        href: "/frontend/pages/teacher?tab=settings",
        icon: Settings,
        permission: Permission.SETTINGS,
    },
    {
        label: "Sign Out",
        action: "logout",
        icon: LogOut,
    },
];



export const SUPERADMIN_SIDEBAR_ITEMS: SidebarItem[] = [
    {
        label: "Dashboard",
        href: "/frontend/pages/superadmin",
        tab: "dashboard",
        icon: Home,
        permission: Permission.DASHBOARD,
    },
    {
        label: "Add School",
        mobileLabel: "Add",
        href: "/frontend/pages/superadmin?tab=addschool",
        tab: "addschool",
        icon: Plus,
        permission: Permission.ADD_SCHOOL,
    },
    {
        label: "Schools",
        href: "/frontend/pages/superadmin?tab=schools",
        tab: "schools",
        icon: Users,
        permission: Permission.SCHOOLS,
    },
    {
        label: "Add Chairman",
        mobileLabel: "Chairman",
        href: "/frontend/pages/superadmin?tab=addchairman",
        tab: "addchairman",
        icon: UserCheck,
        permission: Permission.SCHOOLS,
    },
    {
        label: "Remove schools",
        mobileLabel: "Remove",
        href: "/frontend/pages/superadmin?tab=removeschools",
        tab: "removeschools",
        icon: Trash2,
        permission: Permission.SCHOOLS,
    },
    {
        label: "Subscriptions",
        href: "/frontend/pages/superadmin?tab=subscriptions",
        tab: "subscriptions",
        icon: Settings2,
        permission: Permission.SCHOOLS,
    },
    {
        label: "Fees Transactions",
        mobileLabel: "Fees",
        href: "/frontend/pages/superadmin?tab=transactions",
        tab: "transactions",
        icon: CreditCard,
        permission: Permission.FEES_TRANSACTIONS,
    },
    {
        label: "Sign Out",
        action: "logout",
        icon: LogOut,
    },
];

export const CHAIRMAN_MENU_ITEMS: SidebarItem[] = [
    {
        label: "Dashboard",
        tab: "dashboard",
        href: "/frontend/pages/chairman?tab=dashboard",
        icon: LayoutDashboard,
        permission: Permission.DASHBOARD,
    },
    {
        label: "Discount Approvals",
        tab: "discount-approvals",
        href: "/frontend/pages/chairman?tab=discount-approvals",
        icon: DollarSign,
        permission: Permission.FEES,
    },
    {
        label: "Settings",
        tab: "settings",
        href: "/frontend/pages/chairman?tab=settings",
        icon: Settings,
        permission: Permission.SETTINGS,
    },
    {
        label: "Sign Out",
        action: "logout",
        icon: LogOut,
    },
];
